name: Build Executables

on:
  release:
    types: [published]

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: "translation-calculator-linux"
          - os: macos-latest
            artifact_name: "translation-calculator-macos"
          - os: windows-latest
            artifact_name: "translation-calculator-windows"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version file
        run: |
          git describe --tags > .version

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12"
          spec: "main.spec"
          requirements: "requirements.txt"
          upload_exe_with_name: ${{ matrix.artifact_name }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*
          asset_name: ${{ matrix.artifact_name }}
          asset_content_type: application/octet-stream