name: Build Executables

on:
  release:
    types: [published]

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to fetch tags
          
      - name: Set version file
        run: |
          git describe --tags > .version
          
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Translation Calculator'