name: Build Executables

on:
  release:
    types: [published]

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: "translation-calculator-linux"
          - os: macos-latest
            artifact_name: "translation-calculator-macos"
          - os: windows-latest
            artifact_name: "translation-calculator-windows"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version file
        run: |
          git describe --tags > .version

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12"
          spec: "main.spec"
          requirements: "requirements.txt"
          upload_exe_with_name: ${{ matrix.artifact_name }}

  add-executables-to-release:
    needs: pyinstaller-build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: translation-calculator-linux

      - name: Download MacOS artifact
        uses: actions/download-artifact@v4
        with:
          name: translation-calculator-macos

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: translation-calculator-windows

      - name: Check artifacts
        run: |
          ls -l

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            translation-calculator-linux.zip
            translation-calculator-macos.zip
            translation-calculator-windows.zip
