name: Build Executables

on:
  release:
    types: [published]

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: 'translation-calculator-linux'
          - os: macos-latest
            artifact_name: 'translation-calculator-macos'
          - os: windows-latest
            artifact_name: 'translation-calculator-windows'
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set version file
        run: |
          git describe --tags > .version
          
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: ${{ matrix.artifact_name }}
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.exe
            dist/**/*.app
            dist/**/translation-calculator-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}